//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GalPro
{
    using System;
    using System.Collections.Generic;
    
    public partial class Satis
    {
        public int SatisId { get; set; }
        public Nullable<int> SubeId { get; set; }
        public Nullable<int> MusteriId { get; set; }
        public Nullable<int> AracId { get; set; }
        public Nullable<System.DateTime> SatisTarih { get; set; }
    }
}
